### ISSUE TITLE
URLs stored by Mosaico should adapt to different domains/bases.

### ISSUE THREAD

**Issue by axon-obriend** [veda-consulting-company/uk.co.vedaconsulting.mosaico#87]
(Original subject: "URLs in civicrm_mosaico_msg_template need to be updated after baseURL update") 

I don't know if this can be addressed in the extension, or if it's really a matter of documentation, but I've run into this twice now: Once when I was moving a site from a staged copy, and another time when switching the site from http: to https:

In both cases, when trying to edit a Mosaico template that had been created when the site was on the old URL, I'd get a blank screen. New templates could be created with no problem. I've discovered that the reason for this is that URLs get stored in the metadata in the table civicrm_mosaico_msg_template. When the site URL changes, the extension is still relying on the URL from the out-of-date metadata. This can cause mixed-content errors when enabling SSL, or completely bad URLs when the site is moved.

I was able to use a [database search and replace utility](https://interconnectit.com/products/search-and-replace-for-wordpress-databases/) to correct them.

Is it possible to store the URLs in a more portable format, similar to how they're specified in the Directories and Resource URL settings? ([civicrm.files] and [civicrm.root])

**Comment by veda-consulting** [comment]
Hi, thanks for the feedback. Yes this issue has come up a few times and
we're in the process of coming up with a solution that will work with
Mosaico. Mosaico's templating mechanism needs the URLs to be fully resolved
in order to render so its not a simple change. Watch this space!

**Comment by axon-obriend** [comment]
Thanks for the update!

**Comment by totten** [comment]
@eileenmcnaughton raised a closely related problem on Mattermost (observed in v2.x). If I understood correctly, the situation was:

 * Use a multisite WP site (multiple URLs/domains for the site, but only one db)
 * In site A, create a template
 * In site B, use the template
 * Observe: the browser throws a cross-origin error trying to read `templates/versafix-1/template-versafix-1.html` from site A

(The pernicious field is probably `civicrm_mosaico_template.metadata -> template`.)

For 2.x, I think we may have a good place to do this normalization: `MosaicoTemplate.create` and `MosaicoTemplate.get` APIs.

**Comment by totten** [comment]
Just to flesh out that last comment a bit... Upstream's data format uses absolute URLs and (at the end of the day) HTML in mailings needs to be generated with an absolute URL (because it loads inside a MUA). But we could add steps to:

 * Normalize -- Convert URLs like `https://civicrm.example.org/sites/default/files/civicrm/foo.jpg` to `[cms.root]/sites/default/files/civicrm/foo.jpg` or `[civicrm.files]/foo.jpg`
 * De-normalize -- Convert URLs like `[civicrm.files]/foo.jpg` to `https://civicrm.example.org/sites/default/files/civicrm/foo.jpg`

We'd probably need to do the (de)normalizing whenever we save/load/send Mosaico templates/mailings.

**Comment by Stoob** [comment]
In a related note, after a domain switch templates were nonfunctional.  I ran this MySQL query to fix the problem.

> UPDATE civicrm_mosaico_template SET metadata = replace(metadata, 'old-domain.org', 'new-domain.org');

**Comment by jdkoelsch** [comment]
@Stoob thank you for providing the query. 

Since this issue has been lingering awhile because it sounds like it may not be easy to resolve, what about providing some documentation on how to handle? I spent some time troubleshooting this issue before I came across this issue. Adding to the extension documentation may save someone else some time.

**Comment by Stoob** [comment]
I created a PR  for the README file @jdkoelsch 

https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/271/files

**Comment by michaelmcandrew** [comment]
@Stoob and @jdkoelsch - did you come across any issues accessing already existing mailings, and decide (or not) to fix them with `UPDATE civicrm_mailing SET template_options=replace(template_options, 'old.example.org', 'new.example.org') WHERE template_type='mosaico';`

**Comment by jdkoelsch** [comment]
No, we didn't, but we were just trying to get this to work at all in non-production environments using database exports of prod. We didn't attempt to update existing mailings.

I can see how this would be very helpful though, so I would suggest maybe another update to documentation until the root cause can be addressed.

**Comment by Stoob** [comment]
Yes I had trouble accessing prior Mosaico mailings, and 

> UPDATE civicrm_mailing...

Fixed this issue @michaelmcandrew

**Comment by michaelmcandrew** [comment]
Good to know - thanks

**Comment by jusfreeman** [comment]
This issue is particularly challenging when CiviCRM site is migrated from one CMS platform to another, eg. Drupal to WordPress.

This requires a series of different SQL replace queries to be executed with differing criteria due to the multiple ways that the same reference to the base CiviCRM URL and CiviCRM files URL are stored in civicrm_mailing and civicrm_mosaico_template tables.

Not fun at all.
